package tictac;


public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bttn11 = new javax.swing.JButton();
        bttn01 = new javax.swing.JButton();
        bttn00 = new javax.swing.JButton();
        bttn02 = new javax.swing.JButton();
        bttn10 = new javax.swing.JButton();
        bttn20 = new javax.swing.JButton();
        bttn21 = new javax.swing.JButton();
        bttn22 = new javax.swing.JButton();
        bttn12 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        lbVez = new javax.swing.JLabel();
        bttnVerificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbX = new javax.swing.JLabel();
        lbO = new javax.swing.JLabel();
        bttnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 10, 380));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 420, 10));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 10, 380));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 420, 10));

        bttn11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn11.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn11ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 100));

        bttn01.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn01.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn01ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, 100));

        bttn00.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn00.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn00ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 100));

        bttn02.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn02.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn02ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 100, 100));

        bttn10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn10.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn10ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, 100));

        bttn20.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn20.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn20ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 100));

        bttn21.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn21.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn21ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 100, 100));

        bttn22.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn22.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn22ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 100, 100));

        bttn12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bttn12.setPreferredSize(new java.awt.Dimension(50, 50));
        bttn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn12ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, 100));

        label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label1.setText("Vez de : ");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lbVez.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbVez.setText("X");
        getContentPane().add(lbVez, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 12, -1, 40));

        bttnVerificar.setText("Verificar");
        bttnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, 40));

        jLabel1.setText("X:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel2.setText("O:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        lbX.setText("0");
        getContentPane().add(lbX, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        lbO.setText("0");
        getContentPane().add(lbO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        bttnClear.setText("Limpar");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });
        getContentPane().add(bttnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 477, 90, 40));

        setSize(new java.awt.Dimension(514, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String vez = "X";
    private void bttn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn00ActionPerformed

        if (vez.equals("X")) {
            bttn00.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn00.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);

    }//GEN-LAST:event_bttn00ActionPerformed

    private void bttn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn01ActionPerformed
        if (vez.equals("X")) {
            bttn01.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn01.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);

    }//GEN-LAST:event_bttn01ActionPerformed

    private void bttn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn02ActionPerformed
        if (vez.equals("X")) {
            bttn02.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn02.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn02ActionPerformed

    private void bttn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn10ActionPerformed
        if (vez.equals("X")) {
            bttn10.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn10.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn10ActionPerformed

    private void bttn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn11ActionPerformed
        if (vez.equals("X")) {
            bttn11.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn11.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn11ActionPerformed

    private void bttn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn12ActionPerformed
        if (vez.equals("X")) {
            bttn12.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn12.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn12ActionPerformed

    private void bttn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn20ActionPerformed
        if (vez.equals("X")) {
            bttn20.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn20.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn20ActionPerformed

    private void bttn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn21ActionPerformed
        if (vez.equals("X")) {
            bttn21.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn21.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn21ActionPerformed

    private void bttn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn22ActionPerformed
        if (vez.equals("X")) {
            bttn22.setText("X");
            vez = "O";
        } else if (vez.equals("O")) {
            bttn22.setText("O");
            vez = "X";
        }
        lbVez.setText(vez);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn22ActionPerformed
    public int contadorX = 0;
    public int contadorO = 0;
    private void bttnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVerificarActionPerformed
        if (bttn00.getText() == bttn11.getText()) { //Diagonal Principal
            if (bttn11.getText() == bttn22.getText()) {
                if (bttn00.getText().equals("X")) {
                    contadorX++;
                } else if (bttn00.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn02.getText() == bttn11.getText()) { //Diagonal Secundária
            if (bttn11.getText() == bttn20.getText()) {
                if (bttn02.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn02.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn00.getText() == bttn01.getText()) { //3 de cima
            if (bttn00.getText() == bttn02.getText()) {
                if (bttn00.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn00.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn10.getText() == bttn11.getText()) { //3 do meio
            if (bttn10.getText() == bttn12.getText()) {
                if (bttn10.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn10.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn20.getText() == bttn21.getText()) { //3 de baixo
            if (bttn20.getText() == bttn22.getText()) {
                if (bttn20.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn20.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn00.getText() == bttn10.getText()) { //3 da esquerda
            if (bttn10.getText() == bttn20.getText()) {
                if (bttn00.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn00.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn01.getText() == bttn11.getText()) { //3 do meio
            if (bttn01.getText() == bttn21.getText()) {
                if (bttn01.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn01.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        if (bttn02.getText() == bttn12.getText()) { //3 da direita
            if (bttn12.getText() == bttn22.getText()) {
                if (bttn02.getText().equals("X")) {
                    contadorX++;
                }
                if (bttn02.getText().equals("O")) {
                    contadorO++;
                }
            }
        }
        String contadorOO = String.valueOf(contadorO);
        lbO.setText(contadorOO);
        
        String contadorXX = String.valueOf(contadorX);
        lbX.setText(contadorXX);
    


    }//GEN-LAST:event_bttnVerificarActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        bttn00.setText(null);
        bttn01.setText(null);
        bttn02.setText(null);
        bttn10.setText(null);
        bttn11.setText(null);
        bttn12.setText(null);
        bttn20.setText(null);
        bttn21.setText(null);
        bttn22.setText(null);
        
    }//GEN-LAST:event_bttnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {

            new Tela().setVisible(true);
        }

    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn00;
    private javax.swing.JButton bttn01;
    private javax.swing.JButton bttn02;
    private javax.swing.JButton bttn10;
    private javax.swing.JButton bttn11;
    private javax.swing.JButton bttn12;
    private javax.swing.JButton bttn20;
    private javax.swing.JButton bttn21;
    private javax.swing.JButton bttn22;
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lbO;
    private javax.swing.JLabel lbVez;
    private javax.swing.JLabel lbX;
    // End of variables declaration//GEN-END:variables
}
